engines:
  duplication:
    enabled: true
    config:
      languages:
      - php
  fixme:
    enabled: true
  phpmd:
    enabled: true
  phpcodesniffer:
    enabled: true
    config:
      standard: "PSR1,PSR2"
  markdownlint:
    enabled: true
ratings:
  paths:
  - "**.php"
  - "**.md"
exclude_paths:
- tests/
- vendor/
